// Author: Avery Roebrtson
// File: main.c
// Use: Testing development for various systems 
//      - Test uploading code with ST-LINKV2
//      - Implement and test UART
//      - Implement and test sonar sensor with UART
//      - Implement and test CAN communication

#include "stdio.h"
#include "stm32f1xx_hal.h"

/* semihosting Initializing */
extern void initialise_monitor_handles(void);

// void SystemClock_Config(void);
static void MX_GPIO_Init(void);

int main(void)
{
    // Initialize the HAL Library
    HAL_Init();
    
    // Configure the system clock
    // SystemClock_Config();
    
    // Initialize GPIO for onboard LED
    MX_GPIO_Init();

    // Main loop
    while (1)
    {
        // Toggle the LED
        HAL_GPIO_TogglePin(GPIOC, GPIO_PIN_13);
        
        // Delay for half a second (500ms)
        HAL_Delay(250);
        initialise_monitor_handles();
        printf("Test test\n\r");
    }
}

// Configure the system clock
// void SystemClock_Config(void)
// {
//     // This is automatically generated by STM32CubeMX. It configures the system clock.
//     // If you need to modify it, you can do so using STM32CubeMX and regenerate the code.
// }

void SysTick_Handler(void)
{
  HAL_IncTick();
}

// GPIO Configuration for PC13 (LED)
static void MX_GPIO_Init(void)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    // Enable the GPIOC clock
    __HAL_RCC_GPIOC_CLK_ENABLE();

    // Configure PC13 as output push-pull
    GPIO_InitStruct.Pin = GPIO_PIN_13;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    // GPIO_InitStruct.Pull = GPIO_NOPULL; 
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_HIGH;
    HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);
}
